### ISSUE TITLE
Migrate to maven-surefire-plugin 2.18.x

### ISSUE THREAD

**Issue by palyuga** [jcabi/jcabi-parent#22]
This version of the plugin contains a fix of bug which causes unit tests hanging (https://github.com/teamed/qulice/issues/303)
The current used version is 2.17

**Comment by dmarkov** [comment]
we'll find someone to do this task, soon

**Comment by dmarkov** [comment]
@jenya please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmarkov** [comment]
@palyuga many thanks for the bug report, I added 15 mins to your acc, transaction `50344750`

**Comment by dmarkov** [comment]
@apocarteres it's yours, please go ahead

**Comment by apocarteres** [comment]
@dmarkov please find someone to review PR https://github.com/jcabi/jcabi-parent/pull/24

**Comment by apocarteres** [comment]
@paluga done. pls confirm

**Comment by palyuga** [comment]
@apocarteres thanks!

**Comment by dmarkov** [comment]
@apocarteres **30 mins** was added to your account, many thanks for your contribution!. +30 added to your rating, at the moment it is: [+165](http://www.netbout.com/b/35111?open=rating)
